### ISSUE TITLE
공동 번역 웹사이트 빌드에 불필요한 Skill Tree 제거

### ISSUE THREAD

**Issue by rlarywnd234** [BonoCocoa/web-skills#6]

**Comment by wisewell** [comment]
1. FUNDAMENTALS ~ 6. FRAMEWORKS & LIBRARIES : rlarywnd234

7. TESTING ~ 13. DATABASES & SERVERS : wisewell

**Comment by wisewell** [comment]
7번 TESTING부터 13. DATABASES & SERVERS까지 맡은 파트 불필요한 스킬 트리 제거 완료
